'use client';
import {useState} from 'react';
import {Eye,EyeOff,ArrowRight,Ticket,Check,Info} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Profile,passwordChecks,validEmail} from '@/lib/cinebook';
export type DemoAccount=Profile&{password:string};
export const DEMO_ACCOUNT:DemoAccount={name:'Alex Morgan',email:'demo@cinebook.lk',password:'CineBook123!'};
export default function AuthDialog({open,onClose,onLogin,accounts,onRegister}:{open:boolean;onClose:()=>void;onLogin:(p:Profile)=>void;accounts:DemoAccount[];onRegister:(p:DemoAccount)=>void}){
 const [mode,setMode]=useState('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[visible,setVisible]=useState(false),[error,setError]=useState('');
 function finish(profile:Profile){onLogin({name:profile.name,email:profile.email});setPassword('');setConfirm('');setError('');onClose();}
 function submit(e:React.FormEvent){e.preventDefault();setError('');const address=email.trim().toLowerCase();if(!validEmail(address)){setError('Enter a valid email address.');return;}if(mode==='login'){const account=[DEMO_ACCOUNT,...accounts].find(a=>a.email===address&&a.password===password);if(!account){setError('Email or password does not match a demo account. Use the demo below, or create a temporary account.');return;}finish(account);}else{if(name.trim().length<2){setError('Enter a name with at least 2 characters.');return;}if(!passwordChecks(password).every(Boolean)){setError('Please meet all three password requirements.');return;}if(password!==confirm){setError('The passwords do not match.');return;}if([DEMO_ACCOUNT,...accounts].some(a=>a.email===address)){setError('This email already has a demo account. Switch to Log in.');return;}const account={name:name.trim(),email:address,password};onRegister(account);finish(account);}}
 return <Dialog open={open} onOpenChange={v=>{if(!v){setPassword('');setConfirm('');setError('');onClose();}}}><DialogContent className="auth-modal"><div className="auth-brand"><Ticket size={29}/><span>CineBook</span></div><DialogTitle>{mode==='login'?'Welcome back.':'Make movie nights yours.'}</DialogTitle><DialogDescription>{mode==='login'?'Log in to try your profile and booking experience.':'Create a temporary profile to explore the complete flow.'}</DialogDescription><Tabs value={mode} onValueChange={v=>{setMode(v);setError('');setPassword('');setConfirm('');}}><TabsList className="auth-tabs"><TabsTrigger value="login">Log in</TabsTrigger><TabsTrigger value="register">Create account</TabsTrigger></TabsList></Tabs><div className="notice"><Info size={18}/><p><b>Frontend demo only.</b> Use sample details and a test password. Accounts last until page refresh; no real account or email is created.</p></div><form onSubmit={submit} className="form-stack">{mode==='register'&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100} required placeholder="Your name" autoComplete="off"/></label>}<label>Email address<input type="email" required maxLength={200} autoComplete="off" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<div className="password-wrap"><input type={visible?'text':'password'} required maxLength={128} autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your test password"/><button type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label>{mode==='register'&&<><div className="password-checks">{['At least 8 characters','Uppercase and lowercase letters','At least one number'].map((text,i)=><span key={text} className={passwordChecks(password)[i]?'met':''}><Check size={13}/>{text}</span>)}</div><label>Confirm password<input type={visible?'text':'password'} required maxLength={128} autoComplete="off" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat your test password"/></label></>}{error&&<p role="alert" className="error">{error}</p>}<button className="primary wide" type="submit">{mode==='login'?'Log in to demo':'Create demo account'}<ArrowRight size={18}/></button></form><div className="demo-login"><p>Just looking around?</p><button className="secondary wide" onClick={()=>finish(DEMO_ACCOUNT)}>Try the demo account <ArrowRight size={17}/></button><small>demo@cinebook.lk · CineBook123!</small></div></DialogContent></Dialog>;
}
