export const MOVIES = [
  {id:'dune',title:'Dune: Part Two',genres:['Sci-fi','Adventure'],minutes:166,rating:'PG-13',year:2024,image:'/images/dune.jpg',tag:'THE BIG-SCREEN EXPERIENCE',description:'Paul Atreides joins the Fremen on a journey of revenge, facing a choice between love and the fate of the universe.',format:'IMAX',times:['11:00','15:00','19:00'],price:2200,hall:1},
  {id:'interstellar',title:'Interstellar',genres:['Sci-fi','Drama'],minutes:169,rating:'PG-13',year:2014,image:'/images/interstellar.jpg',tag:'BACK ON THE BIG SCREEN',description:'A team of explorers travels beyond this galaxy to discover whether mankind has a future among the stars.',format:'2D',times:['10:30','14:30','18:30'],price:1500,hall:2},
  {id:'batman',title:'The Batman',genres:['Action','Crime'],minutes:176,rating:'PG-13',year:2022,image:'/images/batman.jpg',tag:'A NIGHT IN GOTHAM',description:'Batman follows a trail of cryptic clues into Gotham’s underworld, where he must forge new relationships to unmask a killer.',format:'DOLBY',times:['11:30','15:30','19:30'],price:1800,hall:3},
];
export const CINEMAS=[{id:'colombo',name:'CineBook Colombo',city:'Colombo',description:'Your city-centre movie escape.'},{id:'kandy',name:'CineBook Kandy',city:'Kandy',description:'Big-screen stories in the hill capital.'}];
export type Movie=typeof MOVIES[number];
export type Profile={name:string;email:string};
export type Booking={id:string;movieId:string;date:string;time:string;cinema:string;seats:string[];name:string;email?:string;total:number;cancelled?:boolean;mode:'demo'|'api';createdAt:string;owner:string};
export type Show={movieId:string;date:string;time:string;cinema:string};
export const API=process.env.NEXT_PUBLIC_BOOKING_API_ENABLED==='true'?(process.env.NEXT_PUBLIC_API_BASE?.replace(/\/$/,'')||''):'';
export const BOOKING_FEE=100;
export const DEMO_OCCUPIED=['C3','C4','D5','D6','F2','F3'];
export const money=(value:number)=>'LKR '+value.toLocaleString('en-LK');
export const duration=(value:number)=>`${Math.floor(value/60)}h ${value%60}m`;
export const cinemaName=(id:string)=>CINEMAS.find(c=>c.id===id)?.name||'CineBook';
export const dateLabel=(date:string)=>date?new Date(date+'T12:00:00+05:30').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Colombo'}):'Choose a date';
export const showStarted=(date:string,time:string,now=Date.now())=>!date||!time||new Date(`${date}T${time}:00+05:30`).getTime()<=now;
export function dateRange(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Colombo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const value=(type:string)=>parts.find(p=>p.type===type)!.value;const today=`${value('year')}-${value('month')}-${value('day')}`;return Array.from({length:7},(_,i)=>{const d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+i);return d.toISOString().slice(0,10);});}
export function makeId(){return 'CB-'+Array.from(crypto.getRandomValues(new Uint8Array(6)),x=>x.toString(16).padStart(2,'0')).join('').toUpperCase();}
export function bookingStatus(b:Booking){return b.cancelled?'Cancelled':showStarted(b.date,b.time)?'Past':'Upcoming';}
export function occupiedSeats(bookings:Booking[],show:Show){return [...new Set([...DEMO_OCCUPIED,...bookings.filter(b=>b.mode==='demo'&&!b.cancelled&&b.movieId===show.movieId&&b.date===show.date&&b.time===show.time&&b.cinema===show.cinema).flatMap(b=>b.seats)])];}
export function suggestSeats(taken:string[],count:number){if(count<1||count>4)return [];for(const row of ['E','D','F','C','G','B','H','A']){for(const start of [3,5,2,6,1,7,4,8]){const group=Array.from({length:count},(_,i)=>row+(start+i));if(start+count-1>8||(start<=4&&start+count-1>4)||group.some(s=>taken.includes(s)))continue;return group;}}return [];}
export function filterMovies(query:string,genre:string,format:string,sort:string,saved?:string[]){return MOVIES.filter(m=>(!saved||saved.includes(m.id))&&`${m.title} ${m.genres.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase())&&(genre==='all'||m.genres.includes(genre))&&(format==='all'||m.format===format)).sort((a,b)=>sort==='price'?a.price-b.price:sort==='duration'?a.minutes-b.minutes:sort==='title'?a.title.localeCompare(b.title):0);}
export class ApiError extends Error{constructor(message:string,public status:number){super(message);}}
export async function apiRequest<T>(path:string,options?:RequestInit):Promise<T>{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(API+path,{...options,signal:controller.signal,headers:{'Content-Type':'application/json',...options?.headers}});let data:unknown;try{data=await r.json();}catch{throw new ApiError('The server returned an unreadable response. Please try again.',r.status);}if(!r.ok)throw new ApiError((data as {message?:string}).message||'Could not complete this request.',r.status);return data as T;}catch(e){if(e instanceof Error&&e.name==='AbortError')throw new Error('The server took too long. Please try again.');throw e;}finally{clearTimeout(timeout);}}
export function downloadText(filename:string,content:string,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function ticketText(b:Booking){const movie=MOVIES.find(m=>m.id===b.movieId)!;return `CINEBOOK — ${b.mode==='demo'?'DEMO TICKET':'RESERVATION'}\n${b.id}\nStatus: ${bookingStatus(b)}\n\n${movie.title}\n${dateLabel(b.date)} at ${b.time} (Sri Lanka time)\n${cinemaName(b.cinema)} • Hall ${movie.hall} • ${movie.format}\nSeats: ${b.seats.join(', ')}\nGuest: ${b.name}\nTickets: ${money(b.seats.length*movie.price)}\nBooking fee: ${money(b.seats.length*BOOKING_FEE)}\nTotal: ${money(b.total)}\n\n${b.cancelled?'CANCELLED — NOT VALID':b.mode==='demo'?'DEMO ONLY — NOT VALID FOR ADMISSION. No payment collected.':'Payment due at the cinema. Present this reservation at the counter.'}`;}
export function downloadTicket(b:Booking){downloadText(b.id+'.txt',ticketText(b));}
export function downloadCalendar(b:Booking){const movie=MOVIES.find(m=>m.id===b.movieId)!;const start=new Date(`${b.date}T${b.time}:00+05:30`);const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const end=new Date(start.getTime()+movie.minutes*60000);downloadText(b.id+'.ics',['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//CineBook//Movie Night//EN','BEGIN:VEVENT',`UID:${b.id}@cinebook.local`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(end)}`,`SUMMARY:${b.mode==='demo'?'Demo movie night - ':''}${movie.title}`,`LOCATION:${cinemaName(b.cinema)} - Hall ${movie.hall}`,`DESCRIPTION:Seats ${b.seats.join(' / ')}. ${b.mode==='demo'?'Demo only; not an admission ticket.':'Pay at cinema.'}`,'END:VEVENT','END:VCALENDAR'].join('\r\n'),'text/calendar;charset=utf-8');}
export function validEmail(email:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);}
export function passwordChecks(password:string){return [password.length>=8,/[a-z]/.test(password)&&/[A-Z]/.test(password),/\d/.test(password)];}
// Local demo session only. No password or credential is ever persisted here.
export function restoreBookings(raw:string|null):Booking[]{try{const data=JSON.parse(raw||'[]');return Array.isArray(data)?data.filter(b=>b&&typeof b.id==='string'&&MOVIES.some(m=>m.id===b.movieId)&&typeof b.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(b.date)&&typeof b.time==='string'&&/^\d{2}:\d{2}$/.test(b.time)&&CINEMAS.some(c=>c.id===b.cinema)&&Array.isArray(b.seats)&&b.seats.length>0&&b.seats.length<=8&&b.seats.every((s:unknown)=>typeof s==='string'&&/^[A-H][1-8]$/.test(s))&&typeof b.name==='string'&&typeof b.owner==='string'&&typeof b.total==='number'&&Number.isFinite(b.total)&&(b.mode==='demo'||b.mode==='api')).slice(0,100):[];}catch{return [];}}
