spring.application.name=cinebook-api
server.port=${PORT:8080}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cinebook}
spring.datasource.username=${DB_USER:cinebook}
spring.datasource.password=${DB_PASSWORD}
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
cinebook.allowed-origin=${FRONTEND_ORIGIN:http://localhost:3000}
server.error.include-message=never
server.error.include-stacktrace=never
server.address=${SERVER_ADDRESS:127.0.0.1}
